--- #YAML:1.0
name: UWO-Directory-Student
abstract: >
  Perform lookups using the University of Western Ontario's student directory
version: 0.02
author:
  - 'Jonathan Yu <frequency@cpan.org>'
license: bsd
distribution_type: module
urls:
  license: http://opensource.org/licenses/bsd-license.php
build_requires:
  Test: 0
  Test::More: 0.62
requires:
  Carp: 1.04
  UWO::Student: 0.02
recommends:
  UWO::Directory: 0
provides:
  UWO::Directory::Student:
    file: lib/UWO/Directory/Student.pm
    version: 0.02
generated_by: hand
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
